import sys
IP=(sys.argv[1])
USR=(sys.argv[2])
PASS=(sys.argv[3])
OPC=(sys.argv[4])
COMP=(sys.argv[5])
LEV=(sys.argv[6])
ASM=(sys.argv[7])
print(IP,USR,PASS,OPC,COMP,LEV,ASM)
contenido = open("/home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/shceduled.sh").read().splitlines()
print(contenido)
contenido.insert(1,"mkdir /home/ebossteam/temp/"+IP)
print("mkdir /home/ebossteam/temp/"+IP)
contenido.insert(2,"cp -r /home/ebossteam/ansibletest/ansible/* /home/ebossteam/home/ebossteam/temp/"+IP)
print("cp -r /home/ebossteam/ansibletest/ansible/* /home/ebossteam/home/ebossteam/temp/"+IP)
contenido.insert(3,"python3 /home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/Inventory.py "+IP+" "+USR+" "+PASS)
print("python3 /home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/Inventory.py "+IP+" "+USR+" "+PASS)
contenido.insert(4,"cp /home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/AUTO.BAT /home/ebossteam/temp/"+IP+"/playbooks/os4690/roles/installation/files/")
print("cp /home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/AUTO.BAT /home/ebossteam/temp/"+IP+"/playbooks/os4690/roles/installation/files/")
contenido.insert(5,"echo "+OPC+" >> /home/ebossteam/temp/"+IP+"/playbooks/os4690/roles/installation/files/AUTO.BAT")
print("echo "+OPC+" >> /home/ebossteam/temp/"+IP+"/playbooks/os4690/roles/installation/files/AUTO.BAT")
contenido.insert(6,"ansible-playbook /home/temp/"+IP+"/playbooks/os4690/Install_Controller.yml -vv  -i /home/ebossteam/temp/"+IP+"/Inventories/import_inventory.yml -e 'level_complement="+COMP+" opc="+OPC+" ASM="+ASM+" level_name="+LEV+"' 2>&1 | tee /var/log/logscontroladores/"+IP+"-$(date +%Y%m%d_%H%M%S).txt")
print("ansible-playbook /home/temp/"+IP+"/playbooks/os4690/Install_Controller.yml -vv  -i /home/ebossteam/temp/"+IP+"/Inventories/import_inventory.yml -e 'level_complement="+COMP+" opc="+OPC+" ASM="+ASM+" level_name="+LEV+"' 2>&1 | tee /var/log/logscontroladores/"+IP+"-$(date +%Y%m%d_%H%M%S).txt")
contenido.insert(7,"rm -r /home/temp/"+IP)
print("rm -r /home/temp/"+IP)
print("")
f = open('/home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/controllers/'+IP+'.sh', "w")
f.writelines("\n".join(contenido))