import sys
IP=(sys.argv[1])
USR=(sys.argv[2])
PASS=(sys.argv[3])
OPC=(sys.argv[4])
COMP=(sys.argv[5])
LEV=(sys.argv[6])
ASM=(sys.argv[7])
FECHA=(sys.argv[8])
VERSION=(sys.argv[9])
# PAQUETES=(sys.argv[10])
EMAIL=(sys.argv[10])
print(IP,USR,PASS,OPC,COMP,LEV,ASM,FECHA,VERSION,EMAIL)
filepath="/var/log/logscontroladores/"+IP+"-"
contenido = open("/home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/shceduled.sh").read().splitlines()
print(contenido)
contenido.insert(1,"mkdir /home/ebossteam/temp/"+IP)
print("mkdir /home/ebossteam/temp/"+IP)
contenido.insert(2,"cp -r /home/ebossteam/ansibletest/ansible/* /home/ebossteam/temp/"+IP)
print("cp -r /home/ebossteam/ansibletest/ansible/* /home/ebossteam/temp/"+IP)
contenido.insert(3,"python3 /home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/Inventory.py "+IP+" "+USR+" "+PASS)
print("python3 /home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/Inventory.py "+IP+" "+USR+" "+PASS)
contenido.insert(4,"cp /home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/AUTO.BAT /home/ebossteam/temp/"+IP+"/playbooks/os4690/roles/installation/files/")
print("cp /home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/AUTO.BAT /home/ebossteam/temp/"+IP+"/playbooks/os4690/roles/installation/files/")
contenido.insert(5,"echo "+OPC+" >> /home/ebossteam/temp/"+IP+"/playbooks/os4690/roles/installation/files/AUTO.BAT")
print("echo "+OPC+" >> /home/ebossteam/temp/"+IP+"/playbooks/os4690/roles/installation/files/AUTO.BAT")
contenido.insert(6,"echo 'changeBat("+filepath+"'$(date +%Y%m%d_%H%M)'.txt)' >> /home/ebossteam/UnattendedInstallation/FULLSTACK/mails/email.py")
print("echo 'changeBat("+filepath+"'$(date +%Y%m%d_%H%M)'.txt)' >> /home/ebossteam/UnattendedInstallation/FULLSTACK/mails/email.py")
contenido.insert(7,"ansible-playbook /home/ebossteam/temp/"+IP+"/playbooks/os4690/Install_Controller.yml -vv  -i /home/ebossteam/temp/"+IP+"/Inventories/import_inventory.yml -e 'level_complement="+COMP+" opc="+OPC+" ASM="+ASM+" level_name="+LEV+"' 2>&1 | tee /var/log/logscontroladores/"+IP+"-$(date +%Y%m%d_%H%M).txt")
print("ansible-playbook /home/ebossteam/temp/"+IP+"/playbooks/os4690/Install_Controller.yml -vv  -i /home/ebossteam/temp/"+IP+"/Inventories/import_inventory.yml -e 'level_complement="+COMP+" opc="+OPC+" ASM="+ASM+" level_name="+LEV+"' 2>&1 | tee /var/log/logscontroladores/"+IP+"-$(date +%Y%m%d_%H%M).txt")
contenido.insert(8,"rm -r /home/ebossteam/temp/"+IP)
print("rm -r /home/ebossteam/temp/"+IP)
contenido.insert(9,"python3 /home/ebossteam/UnattendedInstallation/FULLSTACK/mails/email.py "+IP+" "+USR+" "+PASS+" "+OPC+" "+LEV+" "+ASM+" "+FECHA+" "+VERSION+" "+EMAIL)
print("python3 /home/ebossteam/UnattendedInstallation/FULLSTACK/mails/email.py "+IP+" "+USR+" "+PASS+" "+OPC+" "+LEV+" "+ASM+" "+FECHA+" "+VERSION+" "+EMAIL)
contenido.insert(10,"node /home/ebossteam/UnattendedInstallation/FULLSTACK/mails/mail.js")
print("node /home/ebossteam/UnattendedInstallation/FULLSTACK/mails/mail.js")
f = open('/home/ebossteam/UnattendedInstallation/FULLSTACK/Back-End/public/Inventories/controllers/'+IP+'.sh', "w")
f.writelines("\n".join(contenido))